# Pre-commit hooks for code quality and consistency
# Install with: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^sdk/cpp/build/
      - id: end-of-file-fixer
        exclude: ^sdk/cpp/build/
      - id: check-yaml
        args: ['--unsafe']  # Allow custom YAML tags
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: detect-private-key

  # Python: Black formatter
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: ['--line-length=100']
        files: ^services/.*\.py$
        exclude: ^services/matchmaker/|^sdk/cpp/build/|^services/client-sdk/build/

  # Python: Flake8 linter
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=100', '--extend-ignore=E203,W503']
        files: ^services/.*\.py$
        exclude: ^services/matchmaker/|^sdk/cpp/build/|^services/client-sdk/build/

  # Python: isort (import sorting)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile=black', '--line-length=100']
        files: ^services/.*\.py$
        exclude: ^services/matchmaker/|^sdk/cpp/build/|^services/client-sdk/build/

  # Python: Security scanning with Bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: ['-ll', '-r', 'services/']
        exclude: ^services/matchmaker/|^sdk/cpp/build/|^services/client-sdk/build/|tests/
        pass_filenames: false

  # Dockerfile linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args: ['--ignore', 'DL3008', '--ignore', 'DL3009']

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: ['-d', '{extends: default, rules: {line-length: {max: 120}, document-start: disable}}']

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: ['--fix', '--disable', 'MD013', 'MD033', 'MD041']
        exclude: ^CHANGELOG.md|^sdk/cpp/build/

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: ['--severity=warning']

  # Commit message linting (Conventional Commits)
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

# Exclude build directories and generated files
exclude: |
  (?x)^(
      sdk/cpp/build/.*|
      services/matchmaker/build/.*|
      services/client-sdk/build/.*|
      .*\.egg-info/.*|
      venv/.*|
      .venv/.*|
      node_modules/.*|
      CHANGELOG.md
  )$
