# Prometheus configuration for multiplayer platform monitoring

global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds
  external_labels:
    environment: 'development'
    project: 'multiplayer-platform'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "alerts/*.yml"
  # - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # API Service
  - job_name: 'api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8080']
        labels:
          service: 'api'
          tier: 'backend'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
          tier: 'monitoring'

  # Future: Matchmaker service
  # - job_name: 'matchmaker'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['matchmaker:8081']
  #       labels:
  #         service: 'matchmaker'
  #         tier: 'backend'

  # Future: Node Exporter for system metrics
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #       labels:
  #         service: 'node-exporter'
  #         tier: 'monitoring'

  # Future: PostgreSQL Exporter
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']
  #       labels:
  #         service: 'postgres'
  #         tier: 'database'

  # Future: Redis Exporter
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
  #       labels:
  #         service: 'redis'
  #         tier: 'cache'
